services:
  # nginx
  web:
    container_name: web
    image: nginx:latest
    ports:
      - '8080:80'
    links:
      - 'php'      
    volumes:
      - ./src:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  # PHP
  php:
    container_name: php
    build:
      dockerfile: Dockerfile
      context: .
#    user: 1000:1000
      args:
        user: ubuntu
        uid: 1000
    ports:
      # laravel
      - '8000:8000'
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mariadb

  # MariaDB Service
  mariadb:
    container_name: db
    image: mariadb:10.9
    ports:
      - '3306:3306'    
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydatabase
    volumes:
      - './mysqldata:/var/lib/mysql'

  # Adminer
  adminer:
    image: adminer:latest
    container_name: adminer
    environment:
      ADMINER_DEFAULT_SERVER: db
    restart: always
    ports:
      - 7777:8080  

# Volumes
volumes:
  mysqldata: